import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <Page>
      <MyName>Lindsey Simon</MyName>

      <VercelAccomplishments>Coming soon! 😜</VercelAccomplishments>

      <SlackWelcomeMessage>
        👋 Hi Vercelians, my name is Lindsey Simon and I am stoked to be
        starting today as a{" "}
        <strong>Software Engineer on the Next.js Live team</strong>. Most
        recently I was working at Quip (Salesforce) as VP, Engineering for their
        Enterprise team.
        <br />
        <br />I write{" "}
        <a href="https://www.commoner.com/" target="_blank" rel="noreferrer">
          music
        </a>
        , and work on{" "}
        <a href="https://songbook.studio" target="_blank" rel="noreferrer">
          a music app hosted on Vercel
        </a>
        , and wrangle my 8 year old daughter Opal when I’m not growing the
        Vercel engineering team.
      </SlackWelcomeMessage>

      <PreVercelAccomplishment>
        Something I’m proud of in my professional career before Vercel was my
        work on Google Translate which dramatically improved the
        time-to-selection for language input and output in addition to
        automatically detecting and setting the value of the input based on
        real-time language detection.
      </PreVercelAccomplishment>
    </Page>
  );
};

const VercelAccomplishments = ({ children }: { children: any }) => (
  <div className={styles.block}>
    <h2>Vercel Accomplishments</h2>
    <div>{children}</div>
  </div>
);

const PreVercelAccomplishment = ({ children }: { children: any }) => (
  <div className={styles.block}>
    <h2>Pre-Vercel Accomplishment</h2>
    <div>{children}</div>
  </div>
);

const SlackWelcomeMessage = ({ children }: { children: any }) => (
  <div className={styles.block}>
    <h2>Slack Welcome Message</h2>
    <div>{children}</div>
  </div>
);

const MyName = ({ children }: { children: any }) => <h1>{children}</h1>;

const Page = ({ children }: { children: JSX.Element | JSX.Element[] }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Vercel Resume: Jane Doe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>{children}</main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
